# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\class roster picker\smallwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_smallwindow(object):
    def setupUi(self, smallwindow):
        smallwindow.setObjectName("smallwindow")
        smallwindow.resize(322, 192)
        self.label = QtWidgets.QLabel(smallwindow)
        self.label.setGeometry(QtCore.QRect(10, 10, 271, 151))
        self.label.setStyleSheet("background-color: rgba(194, 194, 194, 0.97);\n"
"border-top-left-radius :28px;\n"
"border-bottom-left-radius :28px;\n"
"border-top-right-radius :28px;\n"
"border-bottom-right-radius :28px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(smallwindow)
        self.label_2.setGeometry(QtCore.QRect(27, 27, 231, 113))
        self.label_2.setStyleSheet("* {\n"
"    color: rgb(98, 105, 112);\n"
"    font-family: \'Microsoft YaHei\';\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(smallwindow)
        self.pushButton.setGeometry(QtCore.QRect(247, 22, 21, 23))
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:4px;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(smallwindow)
        self.pushButton.clicked.connect(smallwindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(smallwindow)

    def retranslateUi(self, smallwindow):
        _translate = QtCore.QCoreApplication.translate
        smallwindow.setWindowTitle(_translate("smallwindow", "Form"))
import res
