# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smallwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_smallwindow(object):
    def setupUi(self, smallwindow):
        smallwindow.setObjectName("smallwindow")
        smallwindow.resize(291, 172)
        self.label = QtWidgets.QLabel(smallwindow)
        self.label.setGeometry(QtCore.QRect(10, 10, 271, 151))
        self.label.setStyleSheet("background-color: rgba(194, 194, 194, 0.97);\n"
"border-top-left-radius :28px;\n"
"border-bottom-left-radius :28px;\n"
"border-top-right-radius :28px;\n"
"border-bottom-right-radius :28px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(smallwindow)
        self.frame.setGeometry(QtCore.QRect(205, 13, 71, 40))
        self.frame.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:4px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_7 = QtWidgets.QPushButton(smallwindow)
        self.pushButton_7.setGeometry(QtCore.QRect(90, 30, 111, 101))
        self.pushButton_7.setStyleSheet("\n"
"QPushButton{\n"
"    border:none;\n"
"}")
        self.pushButton_7.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/picker.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_3 = QtWidgets.QLabel(smallwindow)
        self.label_3.setGeometry(QtCore.QRect(37, 26, 64, 16))
        self.label_3.setStyleSheet("#label_3{\n"
"    color: rgb(98, 105, 112);\n"
"    font-size: 13px; \n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(smallwindow)
        self.label_2.setGeometry(QtCore.QRect(27, 29, 231, 111))
        self.label_2.setStyleSheet("* {\n"
"    color: rgb(98, 105, 112);\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.pushButton_7.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.frame.raise_()

        self.retranslateUi(smallwindow)
        QtCore.QMetaObject.connectSlotsByName(smallwindow)

    def retranslateUi(self, smallwindow):
        _translate = QtCore.QCoreApplication.translate
        smallwindow.setWindowTitle(_translate("smallwindow", "Form"))
import ui1_rc
