# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\class roster picker\picker.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(703, 406)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/picker.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 681, 391))
        self.label.setStyleSheet("background-color: rgba(42, 45, 47, 0.81);\n"
"border-top-left-radius :28px;\n"
"border-bottom-left-radius :28px;\n"
"border-top-right-radius :28px;\n"
"border-bottom-right-radius :28px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 681, 391))
        self.label_2.setStyleSheet("border-image: url(:/images/(1070).webp);\n"
"border-top-left-radius :28px;\n"
"border-bottom-left-radius :28px;\n"
"border-top-right-radius :28px;\n"
"border-bottom-right-radius :28px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(600, 20, 81, 40))
        self.frame.setStyleSheet("\n"
"QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:4px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(60, 70, 591, 121))
        self.label_3.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"* {\n"
"    font-size: 60px;\n"
"}")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(60, 210, 241, 151))
        self.listWidget.setStyleSheet("         QListWidget{background-color:#2B2B2B;color:white}\n"
"         QScrollBar:vertical{\n"
"             width:12px;\n"
"             border:1px solid #2B2B2B;\n"
"             margin:0px,0px,0px,0px;\n"
"             padding-top:0px;\n"
"             padding-bottom:0px;\n"
"         }\n"
"         QScrollBar::handle:vertical{\n"
"             width:3px;\n"
"             background:#4B4B4B;\n"
"             min-height:3;\n"
"         }\n"
"         QScrollBar::handle:vertical:hover{\n"
"             background:#3F3F3F;\n"
"             border:0px #3F3F3F;\n"
"         }\n"
"         QScrollBar::sub-line:vertical{\n"
"             width:0px;\n"
"             border-image:url(:/Res/scroll_left.png);\n"
"             subcontrol-position:left;\n"
"         }\n"
"         QScrollBar::sub-line:vertical:hover{\n"
"             height:0px;\n"
"             background:#323232;\n"
"             subcontrol-position:top;\n"
"         }\n"
"         QScrollBar::add-line:vertical{\n"
"             height:0px;\n"
"             border-image:url(:/Res/scroll_down.png);\n"
"             subcontrol-position:bottom;\n"
"         }\n"
"         QScrollBar::add-line:vertical:hover{\n"
"             height:0px;\n"
"             background:#3F3F3F;\n"
"             subcontrol-position:bottom;\n"
"         }\n"
"         QScrollBar::add-page:vertical{\n"
"             background:#2B2B2B;\n"
"         }\n"
"         QScrollBar::sub-page:vertical{\n"
"             background:#2B2B2B;\n"
"         }\n"
"         QScrollBar::up-arrow:vertical{\n"
"             border-style:outset;\n"
"             border-width:0px;\n"
"         }\n"
"         QScrollBar::down-arrow:vertical{\n"
"             border-style:outset;\n"
"             border-width:0px;\n"
"         }\n"
"\n"
"         QScrollBar:horizontal{\n"
"             height:12px;\n"
"             border:1px #2B2B2B;\n"
"             margin:0px,0px,0px,0px;\n"
"             padding-left:0px;\n"
"             padding-right:0px;\n"
"         }\n"
"         QScrollBar::handle:horizontal{\n"
"             height:16px;\n"
"             background:#4B4B4B;\n"
"             min-width:20;\n"
"         }\n"
"         QScrollBar::handle:horizontal:hover{\n"
"             background:#3F3F3F;\n"
"             border:0px #3F3F3F;\n"
"         }\n"
"         QScrollBar::sub-line:horizontal{\n"
"             width:0px;\n"
"             border-image:url(:/Res/scroll_left.png);\n"
"             subcontrol-position:left;\n"
"         }\n"
"         QScrollBar::sub-line:horizontal:hover{\n"
"             width:0px;\n"
"             background:#2B2B2B;\n"
"             subcontrol-position:left;\n"
"         }\n"
"         QScrollBar::add-line:horizontal{\n"
"             width:0px;\n"
"             border-image:url(:/Res/scroll_right.png);\n"
"             subcontrol-position:right;\n"
"         }\n"
"         QScrollBar::add-line:horizontal:hover{\n"
"             width:0px;\n"
"             background::#2B2B2B;\n"
"             subcontrol-position:right;\n"
"         }\n"
"         QScrollBar::add-page:horizontal{\n"
"                    background:#2B2B2B;\n"
"         }\n"
"         QScrollBar::sub-page:horizontal{\n"
"                     background:#2B2B2B;\n"
"         }\n"
"*{font-size:18px;}")
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setObjectName("listWidget")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(337, 211, 131, 141))
        self.frame_2.setStyleSheet("* {\n"
"    font-size: 11px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    font-size: 15px; /* 设置默认显示的字体大小 */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    font-size: 15px; /* 设置下拉列表中项目的字体大小 */\n"
"}\n"
"")
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(8)
        self.comboBox.setMinimumContentsLength(0)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setStyleSheet("QLabel {\n"
"    color: #FFFFFF;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox.setStyleSheet("* {\n"
"    font-size: 15px;\n"
"}")
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(999999)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 30, 31, 23))
        self.pushButton_4.setStyleSheet("\n"
"QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:4px;\n"
"}")
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(90, 30, 491, 21))
        self.progressBar.setStyleSheet(" QProgressBar {\n"
"        border: 2px solid rgba(88, 88, 88, 0.81);\n"
"        border-radius: 2px;\n"
"        background-color: rgba(0, 0, 0, 0);\n"
"    }\n"
"\n"
"    QProgressBar::chunk {\n"
"        background-color: QLinearGradient(\n"
"            x1: 0, y1: 0, x2: 1, y2: 1,\n"
"            stop: 0 #00BCD4, stop: 1 #8BC34A\n"
"        );\n"
"        border-radius: 8px;\n"
"    }")
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(490, 210, 161, 181))
        self.frame_3.setStyleSheet("* {\n"
"    font-size: 12px; \n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton_5.setStyleSheet("QPushButton{background:rgba(237, 237, 237, 1);border-radius:5px;}QPushButton:hover{background:rgba(210, 210, 210, 0.6);}")
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/swindow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(16, 18))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    font-size: 18px;\n"
"}\n"
"QPushButton{background:rgba(118, 218, 96, 1);border-radius:5px;}QPushButton:hover{background:rgba(80, 182, 84, 1);}")
        self.pushButton_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setIconSize(QtCore.QSize(19, 19))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.label_2.raise_()
        self.label.raise_()
        self.frame.raise_()
        self.label_3.raise_()
        self.listWidget.raise_()
        self.frame_2.raise_()
        self.pushButton_4.raise_()
        self.progressBar.raise_()
        self.frame_3.raise_()

        self.comboBox.setCurrentIndex(-1)
        self.pushButton_3.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

import res
