# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'msgbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_msgbox(object):
    def setupUi(self, msgbox):
        msgbox.setObjectName("msgbox")
        msgbox.resize(311, 285)
        self.gridLayout = QtWidgets.QGridLayout(msgbox)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(msgbox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(msgbox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(msgbox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(msgbox)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(msgbox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)

        self.retranslateUi(msgbox)
        QtCore.QMetaObject.connectSlotsByName(msgbox)

    def retranslateUi(self, msgbox):
        _translate = QtCore.QCoreApplication.translate
        msgbox.setWindowTitle(_translate("msgbox", "msgbox"))
        self.pushButton.setText(_translate("msgbox", "确认保存"))
        self.pushButton_2.setText(_translate("msgbox", "取消"))
        self.label.setText(_translate("msgbox", "您正在保存:xxx"))
        self.label_2.setText(_translate("msgbox", "修改后的名单中共有xxx个名字"))
        self.label_3.setText(_translate("msgbox", "与源文件相比："))
